name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Black
        run: black --check .

      - name: Lint with Flake8
        run: flake8 .

      - name: Smoke-test auto_trainer
        run: |
          mkdir -p scripts/face_data/_ci_test
          touch scripts/face_data/_ci_test/dummy.jpg
          timeout 15 python scripts/auto_trainer.py \
            --face_data scripts/face_data \
            --train_script scripts/train_face1.py || echo "auto_trainer ran"

  # Docker build removed as repository does not include Dockerfile
  # If you add a Dockerfile later, you can re-enable this job
  # docker-build:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Build Docker image
  #       run: |
  #         docker build -t myorg/behavior-monitor:latest .

  #     - name: Log in to GitHub Container Registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Push Docker image
  #       run: |
  #         docker push ghcr.io/${{ github.repository }}/behavior-monitor:latest
